services:
    postgres:
        image: postgres:16-alpine
        container_name: dancehub-postgres
        restart: unless-stopped
        environment:
            POSTGRES_USER: dancehub
            POSTGRES_PASSWORD: dancehub123
            POSTGRES_DB: dancehub
            POSTGRES_HOST_AUTH_METHOD: md5
        command: postgres -c listen_addresses='*'
        ports:
            - '5432:5432'
        volumes:
            - postgres_data:/var/lib/postgresql/data
            - ./docker/postgres/init.sh:/docker-entrypoint-initdb.d/init.sh
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready -U dancehub']
            interval: 10s
            timeout: 5s
            retries: 5

    redis:
        image: redis:7-alpine
        container_name: dancehub-redis
        restart: unless-stopped
        ports:
            - '6380:6379'
        volumes:
            - redis_data:/data
        healthcheck:
            test: ['CMD', 'redis-cli', 'ping']
            interval: 10s
            timeout: 5s
            retries: 5

volumes:
    postgres_data:
        driver: local
    redis_data:
        driver: local
