export type StorageField =
    | 'id'
    | 'filename'
    | 'originalName'
    | 'mimeType'
    | 'extension'
    | 'size'
    | 'path'
    | 'provider'
    | 'providerId'
    | 'visibility'
    | 'status'
    | 'userId'
    | 'metadata'
    | 'createdAt'
    | 'updatedAt';
